import { AntdRegistry } from '@ant-design/nextjs-registry';
import { App } from 'antd';
import type { Metadata } from 'next';

import { geistMono, geistSans } from '@/fonts';

import { DefaultLayout } from '@/layout';
import AppConfigProvider from './_providers/AppConfigProvider';
import '@/globals.css';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

const locale = 'ru';

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang={locale}>
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                <AntdRegistry>
                    <AppConfigProvider locale={locale}>
                        <App>
                            <DefaultLayout>{children}</DefaultLayout>
                        </App>
                    </AppConfigProvider>
                </AntdRegistry>
            </body>
        </html>
    );
}
